cart/urls.py
from django.urls import path

from . import views

app_name='cart'


urlpatterns = [
    path('registrace/', views.SignUp.as_view(), name='sign_up'),
    path('add_from_detail/<slug>/', views.add_to_cart_from_detail, name='add_item_from_detail'),
    path('create-new-cart/', views.create_new_cart, name='create_new_cart'),
    path('', views.cart_view, name='cart_view'),
    path('active-this-cart/<int:cart_id>/', views.active_this_cart, name='active_this_cart'),
    path('active-this-cart-and-home/<int:cart_id>/', views.active_this_cart_and_home, name='active_this_cart_and_home'),
    path('add/<slug>/<int:item_size>/<int:cart_id>', views.increase_item, name='increase_item'),
    path('add_image_to_cart/<int:cart_id>/<int:image_id>/', views.add_image_to_cart, name='add_image_to_cart'),
    path('remove_image_from_cart/<int:cart_id>/<int:image_id>/', views.remove_image_from_cart, name='remove_image_from_cart'),
    path('remove/<slug>/<int:item_size>/<int:cart_id>', views.decrease_item, name='decrease_item'),
    path('delete/<slug>/<int:item_size>/<int:cart_id>', views.delete_item, name='delete_item'),
    path('delete_cart/<int:cart_id>/', views.delete_cart, name='delete_cart'),
    path('logout-in/', views.logout_in, name='logout_in'),
    path('migrate_temp_user/', views.migrate_temp_user, name='migrate_temp_user'),
    path('login_by_hash/<hash>/', views.login_by_hash, name='login_by_hash'),
]

products/urls.py
from django.urls import path

from . import views

app_name='products'

urlpatterns = [
    path('', views.index_view, name='home'),
    path('detail/<slug>/', views.tshirt_detail, name='detail'),
    path('update_description/<slug>/', views.DescriptionUpdate.as_view(), name='update_description'),
]

tshirts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from . import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('products.urls')),
    path('galerie/', include('gallery.urls')),
    path('kosik/', include('cart.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

from django.contrib.auth import get_user_model
from products.models import Tshirt, Size, ProductsSettings
from gallery.models import Image

from products.apps import get_price_with_tax




# Get the user model
User = get_user_model()

# Items model
class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Tshirt, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.SET_NULL, null=True, default='1')
    quantity = models.IntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Tričko {self.item.title}, {self.item.color} - {self.quantity} Ks'

    def get_total(self):
        #return format(self.item.price * self.quantity,",").replace(",", " ")
        return self.item.price * self.quantity

    def get_total_with_tax(self):
        DPH = ProductsSettings.objects.get(pk=1)
        return get_price_with_tax(self.item.price * self.quantity, DPH.DPH)

# Order Model 
class Order(models.Model):
    orderitems = models.ManyToManyField(Item)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    def __str__(self):
        return 'Nákupní košík č.: ' + str(self.id) + ' Pacient: ' + self.user.first_name + ' ' + self.user.last_name

    def get_totals(self):
        total = 0
        for order_item in self.orderitems.all():
            total = total + order_item.get_total()
        
        return total


    def get_totals_with_tax(self):
        total = 0
        DPH = ProductsSettings.objects.get(pk=1)
        for order_item in self.orderitems.all():
            total = total + get_price_with_tax(order_item.get_total(), DPH.DPH)
        
        return total

cart/views.py
#!/usr/bin/python3.8

from django.shortcuts import render, get_object_or_404, redirect, reverse, HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy, reverse
from django.views import generic

from django.contrib import messages

from products.models import Tshirt, Size
from .models import Item, Order
from gallery.models import Image

from django.contrib.auth.models import User
from random import randint
from django.contrib.auth import authenticate, login, logout


def check_if_temp_user_exists_and_log_in(request):
    temp_user = request.session.get('temporary_user_id', None)
    if temp_user:
        u = User.objects.get(pk=temp_user)
        return login(request, u)
    else:
        pass

def get_random_number_as_name() -> int:
    return int(randint(1, 100000))

def create_anonymous_user(rand_number: User) -> User:
    u = User(username=rand_number, first_name='User', last_name=rand_number)
    u.set_unusable_password()
    u.save()

    u.username = u.id
    u.save()
    return u

def anonymous_or_real(request):

    check_if_temp_user_exists_and_log_in(request)
    
    user = request.user
    if user.is_authenticated:
        pass
    else:
        rand_number = get_random_number_as_name()
        u = create_anonymous_user(rand_number)

        request.session['temporary_user_id'] = u.id
        return login(request, u)


"""
def anonymous_or_real(request):

    temp_user = request.session.get('temporary_user_id', None)
    if temp_user:
        u = User.objects.get(pk=temp_user)
        login(request, u)


    user = request.user
    if user.is_authenticated:
        return user
    else:
        # if not, create an anonymous user and log them in
        rand_numb = randint(0, 100000)
        username = randint(0, 100000)
        u = User(username=username, first_name='User', last_name=rand_numb)
        u.set_unusable_password()
        u.save()

        u.username = u.id
        u.save()

        request.session['temporary_user_id'] = u.id

        #authenticate(user=u)
        login(request, u)
        return u
"""

def logout_in(request):
    temp_user = request.session.get('temporary_user_id', None)
    logout(request)

    request.session['temporary_user_id'] = temp_user
    return redirect("login")


def migrate_temp_user(request):
    # Check 
    temp_user = request.session.get('temporary_user_id', None)
    if temp_user:
        carts = Order.objects.filter(user=temp_user)
        for cart in carts:
            cart.user = request.user
            cart.save()
            cart_id = cart.id
            active_this_cart(request, cart_id)  

        items = Item.objects.filter(user=temp_user)
        for item in items:
            item.user = request.user
            item.save()

        images = Image.objects.filter(user=temp_user)
        for image in images:
            image.user = request.user
            image.save()

        del request.session['temporary_user_id']
    else: 
        pass
    return redirect("products:home")

def login_by_hash(request, hash):
    u = User.objects.get(password=hash)
    login(request, u)
    return redirect("products:home")


# Sign up
class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('cart:logout_in')
    template_name = 'cart/signup.html'


# Adds item from product detail
def add_to_cart_from_detail(request, slug):
    anonymous_or_real(request)
    item_size = Size.objects.get(pk=request.POST['size'])
    return add_to_cart(request, slug, item_size)

# Increases quantity of item in cart
def increase_item(request, slug, item_size, cart_id):
    active_this_cart(request, cart_id)
    return add_to_cart(request, slug, item_size)

# Adds tshirt to the shopping cart.

def add_to_cart(request, slug, item_size):
    item = get_object_or_404(Tshirt, slug=slug) # Gets t-shirt e.g. "classic-bílá"
    item_size = item_size

    this_order, created = Order.objects.get_or_create(user=request.user, ordered=False, active=True)# Gets active cart
    item_qs = this_order.orderitems.filter(item=item, size=item_size, user=request.user)# Gets t-shirt e.g. "classic-bílá" in a active cart

    if item_qs.exists():
        order_item = this_order.orderitems.get(item=item, size=item_size, user=request.user)
    else:
        order_item = Item.objects.create(item=item, size=item_size, user=request.user)
    
    # Gets existing order or creates new one. 
    # Gets existing tshirt and increases quantity or creates new one.

    order_qs = Order.objects.filter(user=request.user, ordered=False, active=True)# Get active cart
    if order_qs.exists(): # If active cart exists
        order = order_qs[0]
        # Check if the order item is in the order.
        if order.orderitems.filter(item__slug=item.slug, size=item_size).exists(): # If in active cart exists t-shirt e.g. "classic-bílá".
            order_item.quantity +=1
            order_item.save()
            messages.info(request, 'Počet triček byl navýšen.')
            return redirect("cart:cart_view")
        else:
            
            # Gets and assigns size of t-shirt from form
            #selected_size = item.size.get(pk=request.POST['size'])
            order_item.size = item_size
            order_item.save()

            # Adds new item 
            order.orderitems.add(order_item)
            messages.info(request, 'Tričko bylo úspěšně přidáno do košíku.')
            return redirect("cart:cart_view")
    else:
        # Gets and assigns size of t-shirt from form
        order_item.size = item_size
        order_item.save()

        # Adds new item 
        order = Order.objects.create(user=request.user)
        order.orderitems.add(order_item)
        order.active = True
        order.save()
        messages.info(request, 'Tričko bylo úspěšně přidáno do košíku.')
        return redirect("cart:cart_view")

# Removes tshirt to the shopping cart.

def decrease_item(request, slug, item_size, cart_id):
    active_this_cart(request, cart_id)
    item = get_object_or_404(Tshirt, slug=slug)
    item_size = item_size
    this_order = Order.objects.get(user=request.user, ordered=False, active=True)
    order_item = this_order.orderitems.get(item=item, size=item_size, user=request.user)

    # Gets existed tshirt and decreases quantity or delete it.

    if order_item.quantity > 1:
        order_item.quantity -=1
        order_item.save()
        messages.info(request, 'Tričko bylo odebráno.')
        return redirect("cart:cart_view")
    else:
        order_item.delete()
        messages.info(request, 'Tričko bylo odstraněno z košíku.')
        return redirect("cart:cart_view")

# Deletes item from shopping cart.

def delete_item(request, slug, item_size, cart_id):
    active_this_cart(request, cart_id)
    item = get_object_or_404(Tshirt, slug=slug)
    this_order = Order.objects.get(user=request.user, ordered=False, active=True)
    order_item = this_order.orderitems.get(item=item, size=item_size, user=request.user)
    order_item.delete()
    messages.info(request, 'Tričko bylo odstraněno z košíku.')
    return redirect("cart:cart_view")


# Creates new cart.

def create_new_cart(request):
    order = Order.objects.create(user=request.user)

    all_carts = Order.objects.filter(user=request.user, ordered=False,)
    count_all_carts = Order.objects.filter(user=request.user, ordered=False,).count()
    cart_id = all_carts[count_all_carts-1].pk
    
    active_this_cart(request, cart_id)

    messages.info(request, 'Nový košík vytvořen.')
    return redirect("cart:cart_view")


# Deletes particular cart

def delete_cart(request, cart_id):

    cart = Order.objects.get(pk=cart_id)
    items = cart.orderitems.all()
    items.delete()
    cart.delete()

    all_carts = Order.objects.filter(user=request.user, ordered=False,)
    count_all_carts = Order.objects.filter(user=request.user, ordered=False,).count()
    cart_id = all_carts[count_all_carts-1].pk
    
    active_this_cart(request, cart_id)

    messages.info(request, 'Košík byl úspěšně smazán.')
    return redirect("cart:cart_view")




def cart_view(request):

    anonymous_or_real(request)

    user = request.user

    carts = Order.objects.filter(user=user, ordered=False).order_by('created')
    gallery = Image.objects.filter(user=user, basic_image=True).order_by('-created')
    images_in_order = Image.objects.filter(user=user, basic_image=False).order_by('created')

    order = [0]
    anchor = 'active_cart'
    

    return render(request, "cart/cart_home.html", { 'order':order, 'carts':carts, 'gallery':gallery, 'images_in_order':images_in_order, 'anchor':anchor,})

def active_this_cart(request, cart_id):

    user = request.user

    # Deactives all other carts as primary
    orders = Order.objects.filter(user=user, ordered=False)
    for order in orders:
        order.active = False
        order.save()

    # Actives current cart as primary
    order = orders.get(pk=cart_id)
    order.active = True
    order.save()
    return redirect("cart:cart_view")

def active_this_cart_and_home(request, cart_id):
    active_this_cart(request,cart_id)
    return redirect("products:home")


def add_image_to_cart(request, cart_id, image_id):

    user = request.user

    image = Image.objects.get(user=user, pk=image_id)
    image.pk = None
    image.basic_image = False
    image.belongs_to_order = cart_id
    image.save()

    active_this_cart(request, cart_id)
    return redirect("cart:cart_view")

def remove_image_from_cart(request, cart_id, image_id):

    user = request.user

    image = Image.objects.get(user=user, pk=image_id)
    image.delete()

    active_this_cart(request, cart_id)
    return redirect("cart:cart_view")







   


    

cart/templates/cart/cart_home.html
{% extends 'products/base.html' %}
{% load humanize %}
{% load cart_tag %}
{% load thumbnail %}

{% block content %}

{% if anchor %}
<script type='text/javascript'>
$(document).ready(function(){
    window.location = '#{{ anchor }}'
});
</script>
{% endif %}


<div class="one-page-cart-content">
    {% for cart in carts %}
    {% if cart.active and forloop.counter > 1 %}<span id="active_cart"></span>{% endif %}
    <div class="one-page-cart-self">
    <a href="#myModal{{cart.id}}" data-toggle="modal"> <span style="float:right">Smazat tento košík <span class="glyphicon glyphicon-trash"></span></span></a>
    <h3><a href="{% url 'cart:active_this_cart' cart.id %}">Košík č. {{forloop.counter}}</a></h3> 
    {% if cart.active %}<span style="color:green; float:left"><b>Aktivní košík</b></span><br>{% endif %}

        {%for image in images_in_order %}
            {% if image.belongs_to_order == cart.id %}
                <div class="images_cart_block">
                    <div class="images_cart_block_image">
                        <a href="{{image.image.url}}" target='_blank'>
                        
                            {% if image.css_class == 'png' or image.css_class == 'jpg' %} 
                                {% thumbnail image.image "x200" crop="center" as thumb %}
                                <img src="{{thumb.url}}" class="images_cart_block_image_thumbnail"  onerror="this.src='https://tshirtsapp.s3.amazonaws.com/template_images/default_image.jpg'">
                                {% endthumbnail %} 
                            {% else %}
                                <img src="{{image.image.url}}" class="images_cart_block_image_thumbnail"  onerror="this.src='https://tshirtsapp.s3.amazonaws.com/template_images/default_image_icon.png'">
                            {% endif %}                       

                        </a></br>
                    </div>
                        <b>Název:</b> {{image.title}} <br>
                        <b>Velikost:</b> {{image.size}} <br>
                        <b>Umístění:</b> {{image.position}} <br>
                        {% if image.note %}<b>Poznámka:</b> {{image.note}} <br>{% endif %} 
                        <a href="{% url 'cart:remove_image_from_cart' cart.id image.id %}">Odebrat z košíku <span class="glyphicon glyphicon-trash"></span></a></br>          
                </div>

            {% endif %}

        {% endfor %}

        {% if  cart.id|number_of_images_in_cart  < 4 %}
        <div class="images_cart_block_new"><a href="#myModal_image{{cart.id}}" data-toggle="modal">Vybrat z Moje galerie <small><span class="glyphicon glyphicon-plus"></span></small></a></div>
        {% endif %}

    <table class="table table-hover  center cart">
        <thead {% if cart.active %} style="background-color:rgb(106, 201, 238)">{% endif %}
            <tr>
                <th scope="col">Tričko</th>
                <th scope="col">Barva</th>
                <th scope="col">Velikost</th>
                <th scope="col">Množství</th>
                <th scope="col"></th>
                <th scope="col">Cena za kus <small>(s DPH)</small></th>
                <th scope="col">Cena za vše <small>(s DPH)</small></th>
                <th></th>
            </tr>
        </thead>

    {%for item in cart.orderitems.all %}
    
    <tr>
        <td><a href="{% url 'products:detail' item.item.slug %}" id="black_font">{{ item.item.title }}</a></td>
        <td>{{ item.item.color}}</td>
        <td>{{ item.size}}</td>
        <td><a href="{% url 'cart:decrease_item' item.item.slug item.size.id cart.id %}" class="glyphicon glyphicon-minus-sign text-info no_under_line"></a>&nbsp;&nbsp;  {{ item.quantity }} Ks&nbsp;
            <a href="{% url 'cart:increase_item' item.item.slug item.size.id cart.id %}" class="glyphicon glyphicon-plus-sign text-info no_under_line"></a></td>
        <td><a href="{% url 'products:detail' item.item.slug %}"><img src="{{ item.item.image.url }}" id="product_cart_image"></a></td>
        <td><span class="green_price">{{ item.item.price_with_tax|intcomma }} Kč <small></small></span></br> </td>
        <td><span class="green_price">{{ item.get_total_with_tax|intcomma }} Kč <small></small></td>  
        <td><a href="#myModal{{cart.id}}-{{ forloop.counter }}" type="button" class="glyphicon glyphicon-remove no_under_line" data-toggle="modal"></a></td>
    </tr>

    <!-- Delete t-shirt from cart pop-up confirmation. - Modal HTML -->
    <div id="myModal{{cart.id}}-{{ forloop.counter }}" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Potvrzení</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Opravdu chcete odstranit tričko <b>{{ item.item.title }}</b> z košíku?</p>
                    <p><img src="{{ item.item.image.url }}" id="product_cart_image"></p>
                    <p class="text-secondary"><small></small></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-lg white-link" data-dismiss="modal"><a href="">Zrušit</a></button>
                    <button type="button" class="btn btn-danger btn-lg white-link"><a href="{% url 'cart:delete_item' item.item.slug item.size.id cart.id %}">Odstranit</a></button>
                </div>
            </div>
        </div>
    </div>

        
    {% endfor %}
    <tr>
        <td colspan="8"><a href="{% url 'cart:active_this_cart_and_home' cart.id %}" class="btn btn-success btn-lg white-link">
             <small><span class="glyphicon glyphicon-plus"></span></small>&nbsp;&nbsp; Přidat trička do tohoto košíku</a></td>
    </tr>
    <tr>
        <td colspan="5"></td>
        <td><b> Cena za tento košík: </b></td>    
        <td> <span class="green_price">{{ cart.get_totals_with_tax|intcomma }} Kč<small> s DPH</small></span></br>{{ cart.get_totals|intcomma }} Kč<small> bez DPH</small></td>
        <td></td>
    </tr>
    </table>
    </div>

    <!-- Delete particular cart pop-up confirmation. - Modal HTML -->
    <div id="myModal{{cart.id}}" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Potvrzení</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Opravdu chcete <b>smazat košík č. {{forloop.counter}}</b> se všemi položkami?</p>
                    {%for image in images_in_order %}
                        {% if image.belongs_to_order == cart.id %}

                            {% if image.css_class == 'png' or image.css_class == 'jpg' %} 
                                {% thumbnail image.image "x200" crop="center" as thumb %}
                                <img src="{{thumb.url}}" id="product_cart_image" onerror="this.src='https://tshirtsapp.s3.amazonaws.com/template_images/default_image.jpg'">
                                {% endthumbnail %} 
                            {% else %}
                                <img src="{{image.image.url}}" id="product_cart_image" onerror="this.src='https://tshirtsapp.s3.amazonaws.com/template_images/default_image_icon.png'">
                            {% endif %}

                        {% endif %}
                    {% endfor %} 
                    <p>{%for item in cart.orderitems.all %}
                        <img src="{{ item.item.image.url }}" id="product_cart_image">
                    {% endfor %}</p>
                    <p class="text-secondary"><small></small></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-lg white-link" data-dismiss="modal"><a href="">Zrušit</a></button>
                    <button type="button" class="btn btn-danger btn-lg white-link"><a href="{% url 'cart:delete_cart' cart.id %}">Odstranit</a></button>
                </div>
            </div>
        </div>
    </div>

    <!-- Select image from gallery. - Modal HTML -->
    <div id="myModal_image{{cart.id}}" class="modal fade">
        <div class="modal-dialog" >
            <div class="modal-content" style="width: 160%; position: absolute; margin-left: -150px;">
                <div class="modal-header">
                    <h5 class="modal-title">Vybrat obrázek z galerie</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Vyberte si obrázek k tisku:</p>
                    {%for image in gallery %}
                        <div class="image_cart_select_block">
                            <a href="{% url 'cart:add_image_to_cart' cart.id image.id %}">
                            
                                {% if image.css_class == 'png' or image.css_class == 'jpg' %} 
                                    {% thumbnail image.image "x200" crop="center" as thumb %}
                                    <img src="{{thumb.url}}" class="image_cart_select_image" onerror="this.src='https://tshirtsapp.s3.amazonaws.com/template_images/default_image.jpg'">
                                    {% endthumbnail %} 
                                {% else %}
                                    <img src="{{image.image.url}}" class="image_cart_select_image" onerror="this.src='https://tshirtsapp.s3.amazonaws.com/template_images/default_image_icon.png'">
                                {% endif %}

                            </a></br>
                            {{ image.position.title }}
                        </div>
                    {% endfor %}
                    <p class="text-secondary"><small></small></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-lg white-link" data-dismiss="modal"><a href="">Zrušit</a></button>
                </div>
            </div>
        </div>
    </div>



{% endfor %}

    <div class="center">
    <a href="{% url 'cart:create_new_cart' %}" class="btn btn-info btn-lg white-link">Vytvořit nový košík 
        <span class="glyphicon glyphicon-shopping-cart"></span></a>
    </div>
</div>

{% endblock %}

cart/templates/cart/signup.html
{% extends 'products/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="login_box">
    <h2>Zaregistrovat se</h2>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy}}
      <button type="submit">Registrovat</button>
    </form>
</div>

{% endblock %}