cart/urls.py
from django.urls import path

from . import views

app_name='cart'


urlpatterns = [
    path('registrace/', views.SignUp.as_view(), name='sign_up'),
    path('add_from_detail/<slug>/', views.add_to_cart_from_detail, name='add_item_from_detail'),
    path('create-new-cart/', views.create_new_cart, name='create_new_cart'),
    path('', views.cart_view, name='cart_view'),
    path('active-this-cart/<int:cart_id>/', views.active_this_cart, name='active_this_cart'),
    path('active-this-cart-and-home/<int:cart_id>/', views.active_this_cart_and_home, name='active_this_cart_and_home'),
    path('add/<slug>/<int:item_size>/<int:cart_id>', views.increase_item, name='increase_item'),
    path('add_image_to_cart/<int:cart_id>/<int:image_id>/', views.add_image_to_cart, name='add_image_to_cart'),
    path('remove_image_from_cart/<int:cart_id>/<int:image_id>/', views.remove_image_from_cart, name='remove_image_from_cart'),
    path('remove/<slug>/<int:item_size>/<int:cart_id>', views.decrease_item, name='decrease_item'),
    path('delete/<slug>/<int:item_size>/<int:cart_id>', views.delete_item, name='delete_item'),
    path('delete_cart/<int:cart_id>/', views.delete_cart, name='delete_cart'),
    path('logout-in/', views.logout_in, name='logout_in'),
    path('migrate_temp_user/', views.migrate_temp_user, name='migrate_temp_user'),
    path('login_by_hash/<hash>/', views.login_by_hash, name='login_by_hash'),
]

gallery/urls.py
from django.urls import path

from . import views
#from .models import unsupported_extension_alert

app_name='gallery'

urlpatterns = [
    path('', views.index_view, name='home'),
    path('nahrat/', views.CreateImage.as_view(), name='create'),
    #path('nepodporovany_soubor/', unsupported_extension_alert, name='unsupported_extension_alert'),
    
]

products/urls.py
from django.urls import path

from . import views

app_name='products'

urlpatterns = [
    path('', views.index_view, name='home'),
    path('detail/<slug>/', views.tshirt_detail, name='detail'),
    path('update_description/<slug>/', views.DescriptionUpdate.as_view(), name='update_description'),
]

tshirts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from . import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('products.urls')),
    path('galerie/', include('gallery.urls')),
    path('kosik/', include('cart.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models

from products.apps import get_price_with_tax


class Category(models.Model):
    sex = models.CharField(max_length=50)

    def __str__(self):
        return self.sex

class Color(models.Model):
    title = models.CharField(max_length=50)
    hexacode = models.CharField(max_length=50, null=True)
    nomen_code = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.title

class Size(models.Model):
    title = models.CharField(max_length=10)
    nomen_code = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.title

class Supplier(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

class Tshirt(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=300)
    slug = models.SlugField()
    cover = models.BooleanField(default=False)
    nomen_code = models.IntegerField(null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, null=True)
    size = models.ManyToManyField(Size)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, default='1')
    image = models.ImageField(upload_to='gallery')  
    price = models.DecimalField(max_digits=25, decimal_places=0)
    created = models.DateTimeField('Created', auto_now_add=True)

    def __str__(self):
        return self.title

    def price_with_tax(self):
        DPH = ProductsSettings.objects.get(pk=1)
        return get_price_with_tax(self.price, DPH.DPH)

class ProductsSettings(models.Model):
    DPH = models.IntegerField(null=True)

products/forms.py
from django import forms
from .models import Tshirt

class ChooseSizeForm(forms.ModelForm):

    class Meta:
        model = Tshirt
        fields=["size"]

products/views.py
#!/usr/bin/python3.8.1

from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect

from django.views import generic
from cart.views import migrate_temp_user

from .models import Tshirt, Category, Supplier, Color
from .adler_stock import load_stock, stock_status
import tempfile


"""
class IndexView(generic.ListView):
    template_name = 'products/index.html'


    def get_queryset(self):
        return Tshirt.objects.filter(cover=True)
"""

def index_view(request):
    object_list = Tshirt.objects.filter(cover=True)
    all_colors = Tshirt.objects.filter().order_by('id')

    return render(request, 'products/index.html', {'object_list': object_list, 'all_colors': all_colors })


def tshirt_detail(request, slug):
    tshirt = get_object_or_404(Tshirt, slug=slug)
    all_colors = Tshirt.objects.filter(nomen_code=tshirt.nomen_code).order_by('id')

    # Get items stock status
    data = load_stock()

    nomen_tshirt = tshirt.nomen_code
    nomen_color = tshirt.color.nomen_code
    nomen_size = tshirt.size.all()
    on_stock = []


    for size in nomen_size:
        nomen = str(nomen_tshirt) + str(nomen_color) + str(size.nomen_code)
        size_and_stock = str(size.title) +' - '+ str(stock_status(data, nomen))
        on_stock.append(size_and_stock)

    return render(request, 'products/detail.html', {'tshirt': tshirt, 'all_colors' : all_colors, 'on_stock' : on_stock,})


class DescriptionUpdate(generic.edit.UpdateView):
    model = Tshirt
    fields = ['description']
    template_name_suffix = '_update'

    def get_context_data(self,**kwargs):
        context = super(DescriptionUpdate,self).get_context_data(**kwargs)
        tshirt = get_object_or_404(Tshirt, slug=self.object.slug)
        context['all_colors'] = Tshirt.objects.filter(nomen_code=tshirt.nomen_code)
        return context

    def get_success_url(self):
        return reverse('products:detail', args=(self.object.slug, ))


def create_new_tshirt(title, slug, price, nomen_code, color):
    title = title 
    slug = slug 
    price = price
    category = Category.objects.create()
    supplier = Supplier.objects.create()
    nomen_code = nomen_code
    color = Color.objects.create(title='Černá')
    image = tempfile.NamedTemporaryFile(suffix=".jpg").name

    tshirt = Tshirt.objects.create(title=title, slug=slug, price=price, category=category, supplier=supplier,
    nomen_code=nomen_code, color=color, image=image,)

    return tshirt

products/templates/products/base.html
<!DOCTYPE html>
<html lang="cs-cz">
<head>
    {% load static %}
    {% load cart_tag %}
    <meta charset="utf-8" >
    <title>E-shop s tričky</title>
    <link rel="stylesheet" type="text/css" href="{% static 'products/style.css' %}">
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css">

</head>

<header>
    {% comment %}Temp user session ID: {{ request.session.temporary_user_id }} Přihlášený uživatel ID: {{request.user.id}} {% endcomment %}
    <div class="flex_box p-4 mb-3 bg-dark" >  
        <span class="login_label">
            {% if user.is_authenticated %}
                {% if user.first_name == 'User' %}
                <a href="{% url 'cart:logout_in' %}">Přihlásit se</a> &nbsp;<span class="glyphicon glyphicon-user"></span>
                <a href="{% url 'cart:sign_up' %}">Registrovat se</a> &nbsp;<span class="glyphicon glyphicon-globe"></span> 
                {% else %}
                Jste přihlášen jako {% if user.last_name %}{{ user.first_name }} {{ user.last_name }}{% else %}{{user.username}}{% endif %}
                   &nbsp;<span class="glyphicon glyphicon-user"></span></br>
                <a style="float:right" href="{% url 'logout' %}"> Odhlásit se</a>
                {% endif %}

            {% else %}
            <a href="{% url 'login' %}">Přihlásit se</a> &nbsp;<span class="glyphicon glyphicon-user"></span>
            <a href="{% url 'cart:sign_up' %}">Registrovat se</a> &nbsp;<span class="glyphicon glyphicon-globe"></span> 
            {% endif %}
            
        </span>
        <div class="white-link" style="text-align:center;">
            <a href="{% url 'products:home' %}" class="btn btn-outline-success btn-lg">
                Textil <span class="glyphicon glyphicon-search"></span></a>
            <a href="{% url 'gallery:home' %}" class="btn btn-outline-success btn-lg">
                Moje galerie <span class="glyphicon glyphicon-picture"></span></a>
            {% if user.is_authenticated %}
            <a href="{% url 'cart:cart_view'%}" class="btn btn-outline-success btn-lg">
                Košík <span class="glyphicon glyphicon-shopping-cart"></span>({{ request.user| cart_total }}ks)</a>
            {% elif request.session.temporary_user_id %}
            <a href="{% url 'cart:cart_view'%}" class="btn btn-outline-success btn-lg">
                Košík <span class="glyphicon glyphicon-shopping-cart"></span>({{ request.session.temporary_user_id| cart_total }}ks)</a>
            {% else %} 
            <a href="{% url 'cart:cart_view'%}" class="btn btn-outline-success btn-lg"> 
                Košík <span class="glyphicon glyphicon-shopping-cart"></span></a>
            {% endif %}    
        </div>      
    </div>

    {% if messages %}
        <div class="messages container mt-3">
            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }}{% endif %}" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            {% endfor %}
        </div>
    {% endif %}

</header>

<body>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

{% block content %}
{% endblock %}
</body>

</html>

products/templates/products/detail.html
{% extends 'products/base.html' %}

{% block content %}

<div class="product_detail_box white-link">
    <img id="product_detail_image" class=" rounded-top border img-thumbnail" src="{{ tshirt.image.url }}" >
    <ul>
    <li><h3>{{ tshirt.title }}</h3></li>
    {% if user.is_superuser %}<li><div style="float:right"><a href="{% url 'products:update_description' tshirt.slug %}">
        <span class="glyphicon glyphicon-pencil text-dark"></span></a></div></li>{% endif %}
    <li><p>{% if 'detail' in request.path %}{{ tshirt.description }}{% endif %}</p>
        {% block content_desc_edit %}
        {% endblock %}</li>
    <li><p><b>Barva:</b> {{ tshirt.color}}</p></li>
    <li><p><b>Vyber si barvu:</b></p> {% for tshirt in all_colors %}<a href="{% url 'products:detail' tshirt.slug %}">
        <div class="color_box" style="background-color:{{ tshirt.color.hexacode }}"></div></a>{% endfor %}</li>
    <li><p><b>Vyber si velikost:</b>

        <form id="sizeForm" action="{% url 'cart:add_item_from_detail' tshirt.slug %}" method="post">
            {% csrf_token %}
            {% for size in tshirt.size.all  %}

                <input type="radio"  name="size" id="size{{ forloop.counter }}" value="{{ size.id }}" {% if size.id == 3  %} checked {% endif %}>
                <label for="size{{ forloop.counter }}"> {{ size.title }} </label>    

            {% endfor %}
        </form> 

    </p></li>
    <li><p><b>Na skladě: </b></p>
    {% for number in on_stock  %}
    {{ number }} ks<br></li>
    {% endfor %}<br>
    <li class="green_price"><h3>Cena {{ tshirt.price_with_tax }} Kč <small>(s DPH)</small></h3></li>
    <li><p>Cena {{ tshirt.price }} Kč <small>(bez DPH)</small></p></li>
    <li><input type="submit" value="Přidat do košíku" form="sizeForm" class="btn btn-success btn-lg text-white">
        <button type="button" class="btn btn-primary btn-lg text-white" style="float:right"><a href="{% url 'products:home' %}">Zpět</a></button></li>
    </ul>
</div>


{% endblock %}

products/templates/products/index.html
{% extends 'products/base.html' %}

{% block content %}



{% for product in object_list %}


    <ul id="product_thumbnail">
            <li><a href="{% url 'products:detail' product.slug %}"> <img class=" rounded-top border img-thumbnail" 
                src="{{ product.image.url }}" ></a></li>
        <div class='card-footer center'>
            <li><strong><h3 class="card-title"> {{ product.title }}</h3></strong></li>
            <li>{% for tshirt in all_colors %}{% if tshirt.nomen_code == product.nomen_code %}
                <a href="{% url 'products:detail' tshirt.slug %}"><div class="color_box_small" style="background-color:{{ tshirt.color.hexacode }}">
                </div></a>{% endif %}{% endfor %}</li><br>
            <li class="green_price">Cena: {{ product.price_with_tax }} Kč <small>(s DPH)</small></li>
            <!--<li><p class="card-text">Cena bez DPH: {{ product.price }} Kč</p></li>-->
        </div>
    </ul>

{% endfor %}


{% endblock %}

products/templates/products/tshirt_update.html
{% extends "products/detail.html" %}

{% block content_desc_edit %}
<div style="width:100%">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Uložit">
</form>
</div>
{% endblock %}